services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: Keycloak.IDP
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    networks:
      - otel

  aspire.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: Aspire.Dashboard
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      - otel

networks:
  otel:
    driver: bridge

