services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: Keycloak.IDP
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    networks:
      - otel

  aspire.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: Aspire.Dashboard
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      - otel

  jaeger:
    image: jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    container_name: Jaeger
    restart: always
    environment:
      - OTEL_ENABLED=true
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
      - "./config.yml:/etc/jaeger/config.yml"
    command: [ "--config", "/etc/jaeger/config.yml" ]
    ports:
      - "0.0.0.0:16686:16686"
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8889:8889"
      - "0.0.0.0:14317:4317" # OTLP gRPC - Changed from 4317:4317 to 14317:4317
      - "0.0.0.0:14318:4318" # OTLP HTTP - Changed from 4318:4318 to 14318:4318
    networks:
      - otel
      - backend

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: Prometheus
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/grafana:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - backend

  loki:
    image: grafana/loki:latest
    container_name: Loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./.containers/loki:/etc/loki
    networks:
      - backend

networks:
  otel:
    driver: bridge
  backend:
    driver: bridge
